% -------------------------------------------------
% STORAGE.PL
% Handles Loading and Saving of OPAC Data
% Role: Integration and Persistence Manager (M3)
% -------------------------------------------------

:- ensure_loaded(data).

% -------------------------------------------------
% LOAD DATA FROM FILE
% -------------------------------------------------
load_data :-
    write('--- Initializing Database Load ---'), nl,
    
    % Memory Management: Clear existing facts to prevent duplication.
    % Satisfies "Allocation/Garbage Collection" requirement.
    retractall(book(_, _, _, _, _, _)),
    retractall(borrower(_, _, _)),
    retractall(loan(_, _, _, _, _, _)),
    retractall(librarian(_, _, _)),
    
    % Portability check for unload_file
    (current_predicate(unload_file/1) -> unload_file('data.pl') ; true),
    
    % Use catch to handle missing file errors gracefully
    catch(ensure_loaded(data), _, (write('>> Warning: No existing database found.'), nl)),
    
    write('>> All records synchronized successfully.'), nl,
    write('-----------------------------------------'), nl.

% -------------------------------------------------
% SAVE DATA TO FILE
% -------------------------------------------------
save_data :-
    write('--- Starting Database Save ---'), nl,

    % 1. Security Backup with Timestamp
    get_time(TS),
    format_time(atom(BK), '%Y%m%d_%H%M%S', TS),
    atomic_list_concat(['backup_data_', BK, '.pl'], BackupFile),
    (exists_file('data.pl') -> copy_file('data.pl', BackupFile) ; true),
    write('>> Security backup created: '), write(BackupFile), nl,

    % 2. Atomic Save (Write to temp, then rename) 
    % This prevents data.pl from being wiped if the program crashes.
    catch((
        tell('data_tmp.pl'),

        % Write Headers and Logic Declarations
        write('% -------------------------------------------------'), nl,
        write('% DATA.PL - AUTOGENERATED DATABASE'), nl,
        write('% -------------------------------------------------'), nl,
        write(':- dynamic book/6.'), nl,
        write(':- dynamic borrower/3.'), nl,
        write(':- dynamic loan/6.'), nl,
        write(':- dynamic librarian/3.'), nl, nl,

        % Save Book Records
        write('% --- BOOK RECORDS ---'), nl,
        forall(book(ID, Title, Author, Year, Copies, Dewey),
            (writeq(book(ID, Title, Author, Year, Copies, Dewey)), write('.'), nl)
        ), nl,

        % Save Borrower Records
        write('% --- BORROWER RECORDS ---'), nl,
        forall(borrower(ID, Name, Course),
            (writeq(borrower(ID, Name, Course)), write('.'), nl)
        ), nl,

        % Save Loan Records
        write('% --- LOAN RECORDS ---'), nl,
        forall(loan(ID, BookID, BorrowerID, DateBorrowed, DueDate, DateReturned),
            (writeq(loan(ID, BookID, BorrowerID, DateBorrowed, DueDate, DateReturned)), write('.'), nl)
        ), nl,

        % Save Librarian Records
        write('% --- LIBRARIAN RECORDS ---'), nl,
        forall(librarian(ID, Name, Position),
            (writeq(librarian(ID, Name, Position)), write('.'), nl)
        ),

        told,
        
        % Final Step: Rename temp file to actual database file
        rename_file('data_tmp.pl', 'data.pl'),
        
        write('>> Books, Borrowers, Loans, and Librarians saved.'), nl,
        write('>> Database persistence complete.'), nl
    ), E, (told, write('>> Error during save: '), write(E), nl)),
    
    write('-----------------------------------------'), nl.